import Head from 'next/head';

export async function getServerSideProps(context) {
  const { slug } = context.params;

  const article = `
    <h1>🔥 Trending Now: ${slug.replace(/_/g, ' ')}</h1>
    <p>This page is updated daily with top global trends in ${slug}.</p>
    <p>Stay ahead with breaking AI news, crypto alerts, and viral topics in your region.</p>
    <a href="https://payhip.com/b/yLYxv" target="_blank">📘 Download the trending eBook now</a>
    <div id="propeller-ad"></div>
  `;

  const meta = {
    title: `${slug.replace(/_/g, ' ')} | RespireWork`,
    description: `Live updates on ${slug.replace(/_/g, ' ')}, generated by AI daily.`,
    slugUrl: `https://www.respirework.com/${slug}`,
  };

  return {
    props: { slug, article, meta },
  };
}

export default function Page({ slug, article, meta }) {
  return (
    <>
      <Head>
        <title>{meta.title}</title>
        <meta name="description" content={meta.description} />
        <meta property="og:title" content={meta.title} />
        <meta property="og:description" content={meta.description} />
        <meta property="og:url" content={meta.slugUrl} />
        <meta name="twitter:card" content="summary" />
        <script
          async
          data-cfasync="false"
          src="//upgulpinon.com/1?z=6052213"
        ></script>
      </Head>
      <main>
        <div dangerouslySetInnerHTML={{ __html: article }} />
      </main>
    </>
  );
}
